# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#


# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
theme: jekyll-theme-so-simple
# remote_theme: mmistakes/so-simple-theme
skin: "/assets/css/skins/doogie.css"
locale: en-US
title: "Jacob 'Doogie' Thomas"
description: "A thought leading technologist, specialising a range of human oriented industries including Events and IoT"
baseurl: "/" # the subpath of your site, e.g. "/blog"
url: https://thatdoogieguy.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
logo: "/assets/images/logo.jpg" # path of site logo, e.g. "/assets/images/logo.png"
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 200
mathjax: true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Roboto"
    weights: "400,400i,700,700i"
google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
twitter:
  username: thatdoogeiguy # site's Twitter username

# Liquid
liquid:
  error_mode: strict

# Build settings
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: true

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  # Recipe defaults
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post
      comments: true
      share: true

# Site Author
author:
  name: Jacob Thomas
  picture: /assets/images/profilephoto.jpg
  email: j@cobthom.as
  twitter: thatdoogieguy
  links:
  - title: LinkedIn
    url: https://linkedin.com/in/thatdoogieguy
    icon: fab fa-linkedin
  - title: Instagram
    url: https://instagram.com/thatdoogieguy
    icon: fab fa-instagram
  - title: GitHub
    url: https://github.com/thatdoogieguy
    icon: fab fa-github-square

# Footer Links
footer_links:
  - title: LinkedIn
    url: https://linkedin.com/in/thatdoogieguy
    icon: fab fa-linkedin
  - title: Instagram
    url: https://instagram.com/thatdoogieguy
    icon: fab fa-instagram
  - title: GitHub
    url: https://github.com/thatdoogieguy
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square

# Copyright
copyright: "This site is hand crafted with the power of Jekyll, GitHub Pages, and all the Open Source developers who make technology possible.
  All content are the personal views and opinions of Jacob Thomas only and do not reflect any third parties."